diagnose PR
jholbrook64/ds-pipelines-targets-3 pull request #3
Opened 2021-09-08 20:12 UTC by jholbrook64

commit to make PR to send to Sam to diagnose what I did wrong

2021-09-14 13:56 UTC, limnoliver requested changes

2021-09-14 13:56 UTC, limnoliver commented on _targets.R
> +  tar_target(wi_data, get_site_data(oldest_active_sites, states[1], parameter[1])),
Now that you've added `get_site_data`, you need to tell `targets` where to find this function, so you'll have to add:

`source("1_fetch/src/get_site_data.r)` to the `_targets.R` file.

2021-09-16 20:17 UTC, jholbrook64 reviewed
@limnoliver, here is the corrected script

2021-09-16 20:20 UTC, limnoliver approved these changes
Maybe just take the `browser()` out now, and you're good to go.

2021-09-16 20:20 UTC, limnoliver commented on 1_fetch/src/find_oldest_sites.R
> +  browser()
Can take this out now? Though it is handy having targets plow through this if you don't specify the callr function.

2021-09-16 20:58 UTC, merged